# Generated by Django 4.1.4 on 2022-12-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Дата Роджения')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatar', verbose_name='Фото')),
            ],
        ),
    ]
