# Generated by Django 4.1.4 on 2022-12-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221226_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Биография'),
        ),
    ]
