# Generated by Django 4.1.3 on 2022-11-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('author', models.CharField(default='Unknown', max_length=50, verbose_name='Автор')),
                ('content', models.TextField(max_length=3000, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('deadline', models.DateField(verbose_name='deadline')),
                ('status', models.CharField(choices=[('new', 'новая'), ('moderated', 'модерированная'), ('rejected', 'откланенная')], default='new', max_length=20, verbose_name='Статус')),
            ],
        ),
    ]
