# Generated by Django 4.1.3 on 2022-11-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('deadline', models.DateField(verbose_name='deadline')),
                ('status', models.CharField(choices=[('new', 'новая'), ('moderated', 'модерированная'), ('rejected', 'откланенная')], default='new', max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
