# Generated by Django 4.1.3 on 2022-11-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_status_type_remove_task_deadline_remove_task_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='webapp.type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
