# Generated by Django 4.1.3 on 2022-12-05 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=500, verbose_name='summary'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('content', models.TextField(max_length=2000, verbose_name='content')),
                ('date_start', models.DateField(verbose_name='the date of the beginning')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='expiration date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_task', to='webapp.project', verbose_name='project')),
            ],
        ),
    ]
