# Generated by Django 4.1.3 on 2022-12-06 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_project_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_task', to='webapp.project', verbose_name='project'),
            preserve_default=False,
        ),
    ]
