# Generated by Django 4.1.4 on 2023-01-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_project_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_deleted',
        ),
    ]
